#!/bin/sh
if [ "$1" = "-k" ]; then
    shift
    curl "http://${1:-localhost}:${2:-8088}/end"
else
    curl -d @sample_webhook_jira.json "http://${1:-localhost}:${2:-8088}/issue-update?user_id=some.employee%40coolCompany.com&user_key=some.employee%40coolCompany.com"
fi
